spec-version: 0.36.0
name: sel4-bv
version: 0.1.0.0
synopsis: TODO
description: TODO
license: BSD-2-Clause
author: Nick Spinale (Colias Group, LLC)
maintainer: Nick Spinale <nick@nickspinale.com>
copyright: Copyright (c) 2025 Colias Group, LLC

language: GHC2021

default-extensions:
  - FunctionalDependencies
  # records
  - OverloadedLabels
  - OverloadedRecordDot
  # GHC2024
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - LambdaCase

ghc-options:
  - -Wall
  - -Wno-unused-do-bind

dependencies:
  - base

internal-libraries:

  smtlib2-types:
    visibility: public
    source-dirs: components/smtlib2-types
    default-extensions:
      - DuplicateRecordFields
      - NoFieldSelectors
    # exposed-modules: # TODO
    dependencies:
      # external
      - deepseq
      - transformers
      - mtl
      - exceptions

  smtlib2:
    visibility: public
    source-dirs: components/smtlib2
    default-extensions:
      - DuplicateRecordFields
      - NoFieldSelectors
    # exposed-modules: # TODO
    dependencies:
      - sel4-bv:smtlib2-types
      # external
      - mtl
      - free
      - text
      - attoparsec
      - megaparsec
      - exceptions
      - process
      - async
      - stm
      - unliftio-core
      - conduit
      - conduit-extra
  
  core:
    visibility: public
    source-dirs: components/core
    default-extensions:
      - DuplicateRecordFields
      - NoFieldSelectors
    exposed-modules:
      - BV.Core.Types
      - BV.Core.Types.Extras
      - BV.Core.Stages
      - BV.Core.AdornProofScript
      - BV.Core.ExecuteSMTProofChecks
    dependencies:
      - sel4-bv:smtlib2-types
      # external
      - deepseq
      - containers
      - transformers
      - mtl
      - exceptions
      - optics-core
      - optics
      - file-embed
      # TODO for debugging
      - filepath
      - pretty-show
      # - pretty-simple

  concrete-syntax:
    visibility: public
    source-dirs: components/concrete-syntax
    default-extensions:
      - DuplicateRecordFields
      - NoFieldSelectors
    exposed-modules:
      - BV.ConcreteSyntax
    dependencies:
      - sel4-bv:core
      - sel4-bv:smtlib2
      # external
      - containers
      - dlist
      - optics-core
      - bytestring
      - text
      - megaparsec
      - attoparsec
      - aeson

  target-dir:
    visibility: public
    source-dirs: components/target-dir
    default-extensions:
      - DuplicateRecordFields
      - NoFieldSelectors
    exposed-modules:
      - BV.TargetDir
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      # external
      - mtl
      - text
      - bytestring
      - aeson
      - filepath

  system:
    visibility: public
    source-dirs: components/system
    default-extensions:
      - DuplicateRecordFields
      - NoFieldSelectors
    # exposed-modules: # TODO
    dependencies:
      - sel4-bv:smtlib2-types
      - sel4-bv:smtlib2
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      # external
      - deepseq
      - containers
      - transformers
      - mtl
      - exceptions
      - free
      - optics-core
      - optics
      - async
      - stm
      - bytestring
      - text
      - base16-bytestring
      - attoparsec
      - megaparsec
      - cryptohash-sha256
      - filepath
      - directory
      - monad-logger
      - unliftio-core
      # TODO prune
      - pretty-show
      # - pretty-simple
      # TODO hack
      - tasty
      - tasty-hunit

  test-utils:
    source-dirs: components/test-utils
    default-extensions:
      - DuplicateRecordFields
      - NoFieldSelectors
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      # external
      - filepath
      # TODO prune
      - pretty-show
      # - pretty-simple

executables:

  cli:
    source-dirs: components/cli
    main: Main.hs
    dependencies:
      - sel4-bv:system
    ghc-options:
      # TODO probably unnecessary here
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  profiling-scratch:
    source-dirs: components/profiling-scratch
    main: Main.hs
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:system
      - sel4-bv:test-utils
      # external
      - text
    ghc-options:
      # TODO probably unnecessary here
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  check-scratch:
    source-dirs: components/check-scratch
    main: Main.hs
    default-extensions:
      - DuplicateRecordFields
      - NoFieldSelectors
    dependencies:
      - sel4-bv:core
      - sel4-bv:system
      - sel4-bv:test-utils
      # external
      - containers
      - filepath
      - optics
    ghc-options:
      # TODO probably unnecessary here
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:

  core-test:
    source-dirs: components/core-test
    main: Main.hs
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      - sel4-bv:system
      - sel4-bv:test-utils
      # external
      - mtl
      - free
      - monad-logger
      - filepath
      - tasty
      - tasty-hunit
    ghc-options:
      # TODO
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  smtlib2-test:
    source-dirs: components/smtlib2-test
    main: Main.hs
    dependencies:
      - sel4-bv:smtlib2-types
      - sel4-bv:smtlib2
      - sel4-bv:target-dir
      # external
      - optics-core
      - mtl
      - text
      - attoparsec
      - megaparsec
      - filepath
      - process
      - Glob
      - tasty
      - tasty-hunit
    ghc-options:
      # TODO
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  concrete-syntax-test:
    source-dirs: components/concrete-syntax-test
    main: Main.hs
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      - sel4-bv:test-utils
      # external
      - mtl
      - text
      - attoparsec
      - megaparsec
      - aeson
      - filepath
      - process
      - Glob
      - tasty
      - tasty-hunit
    ghc-options:
      # TODO
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  system-test:
    source-dirs: components/system-test
    main: Main.hs
    dependencies:
      - sel4-bv:system
    ghc-options:
      # TODO
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
