spec-version: 0.36.0
name: sel4-bv
version: 0.1.0.0
synopsis: TODO
description: TODO
license: BSD-2-Clause
author: Nick Spinale (Colias Group, LLC)
maintainer: Nick Spinale <nick@nickspinale.com>
copyright: Copyright (c) 2025 Colias Group, LLC

language: GHC2024

default-extensions:
  - FunctionalDependencies
  # records
  - DuplicateRecordFields
  - NoFieldSelectors
  - OverloadedLabels
  - OverloadedRecordDot

ghc-options:
  - -Wall
  - -Wno-unused-do-bind

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

_test-ghc-options: &test-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

dependencies:
  - base
  - deepseq
  - parallel
  - transformers
  - transformers-base
  - mtl
  - exceptions
  - safe-exceptions
  - containers
  - array
  - vector
  - bytestring
  - text
  - stm
  - async
  - optics

internal-libraries:

  smtlib2:
    visibility: public
    source-dirs: components/smtlib2
    exposed-modules:
      - BV.SMTLIB2
      - BV.SMTLIB2.Command
      - BV.SMTLIB2.Monad
      - BV.SMTLIB2.SExpr
      - BV.SMTLIB2.SExpr.Show
      - BV.SMTLIB2.SExpr.Read
      - BV.SMTLIB2.SExpr.Build
      - BV.SMTLIB2.SExpr.Build.Pretty
      - BV.SMTLIB2.SExpr.Parse.Attoparsec
      - BV.SMTLIB2.SExpr.Parse.Megaparsec
    dependencies:
      - binary
      - attoparsec
      - megaparsec

  smtlib2-process:
    visibility: public
    source-dirs: components/smtlib2-process
    exposed-modules:
      - BV.SMTLIB2.Process
    dependencies:
      - sel4-bv:smtlib2
      # external
      - process
      - unliftio-core
      - conduit
      - conduit-extra

  logging:
    visibility: public
    source-dirs: components/logging
    exposed-modules:
      - BV.Logging
    dependencies:
      - binary
      - attoparsec
      - aeson
      - attoparsec-aeson
      - unliftio-core
      - monad-logger
  
  network-transport-static:
    visibility: public
    source-dirs: components/network-transport-static
    exposed-modules:
      - Network.Transport.Static
      - Network.Transport.Static.Utils
    dependencies:
      - binary
      - process
      - network-transport

  core:
    visibility: public
    source-dirs: components/core
    exposed-modules:
      - BV.Core.DecorateProofScript
      - BV.Core.ExecuteSMTProofChecks
      - BV.Core.Logic
      - BV.Core.ModelConfig
      - BV.Core.Prelude
      - BV.Core.RepGraph
      - BV.Core.Stages
      - BV.Core.Structs
      - BV.Core.Types
      - BV.Core.Types.Extras.Expr # TODO
      - BV.Core.Types.Extras.Problem # TODO
      - BV.Core.Types.Extras.Program # TODO
      - BV.Core.Types.Extras.ProofCheck # TODO
      - BV.Core.Types.Extras.SExprWithPlaceholders # TODO
      - BV.Core.Utils.IncludeExcludeFilter
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:utils
      # external
      - binary
      - vector-binary-instances
      - file-embed
      - split
      # TODO for debugging
      - filepath
      - pretty-show
      # - pretty-simple

  concrete-syntax:
    visibility: public
    source-dirs: components/concrete-syntax
    exposed-modules:
      - BV.ConcreteSyntax
    dependencies:
      - sel4-bv:core
      - sel4-bv:smtlib2
      # external
      - dlist
      - megaparsec
      - attoparsec
      - aeson
      - aeson-pretty

  utils:
    visibility: public
    source-dirs: components/utils
    exposed-modules:
      - BV.Utils

  target-dir:
    visibility: public
    source-dirs: components/target-dir
    exposed-modules:
      - BV.TargetDir
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      # external
      - aeson
      - filepath

  system-utils:
    visibility: public
    source-dirs: components/system-utils
    # exposed-modules: # TODO
    dependencies:
      - unliftio-core
      - monad-logger

  system-core:
    visibility: public
    source-dirs: components/system-core
    exposed-modules:
      - BV.System.Core
      - BV.System.Core.Utils.Logging # TODO
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:smtlib2-process
      - sel4-bv:logging
      - sel4-bv:core
      - sel4-bv:search-core
      - sel4-bv:concrete-syntax
      - sel4-bv:utils
      - sel4-bv:system-utils
      # external
      - binary
      - unliftio-core
      - monad-logger
      - process
      - base16-bytestring
      - cryptohash-sha256

  search-core:
    visibility: public
    source-dirs: components/search-core
    exposed-modules:
      - BV.Search.Core
      - BV.Search.Core.Solver
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:logging
      - sel4-bv:core
      - sel4-bv:utils

  search-system-core:
    visibility: public
    source-dirs: components/search-system-core
    exposed-modules:
      - BV.Search.System.Core
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:smtlib2-process
      - sel4-bv:logging
      - sel4-bv:core
      - sel4-bv:search-core
      - sel4-bv:utils
      - sel4-bv:system-utils
      - sel4-bv:system-core
      # external
      - binary
      - unliftio-core
      - monad-logger
      - process

  system:
    visibility: public
    source-dirs: components/system
    # exposed-modules: # TODO
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:smtlib2-process
      - sel4-bv:logging
      - sel4-bv:core
      - sel4-bv:search-core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      - sel4-bv:utils
      - sel4-bv:system-utils
      - sel4-bv:system-core
      # external
      - unliftio-core
      - monad-logger
      - binary
      - filepath
      - directory
      - sqlite-simple
      - network-transport
      - distributed-process
      - distributed-process-async

  test-utils:
    source-dirs: components/tests/test-utils
    dependencies:
      - sel4-bv:logging
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      # external
      - tagged
      - unliftio-core
      - monad-logger
      - resourcet
      - filepath
      - directory
      - tasty
      - tasty-hunit
      - optparse-applicative
      # TODO prune
      - pretty-show
      # - pretty-simple

executables:

  sel4-bv-cli:
    source-dirs: components/cli
    main: BV.CLI.Main
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:smtlib2-process
      - sel4-bv:logging
      - sel4-bv:core
      - sel4-bv:search-core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      - sel4-bv:system-utils
      - sel4-bv:system
      - sel4-bv:system-core
      - sel4-bv:network-transport-static
      # external
      - megaparsec
      - attoparsec
      - aeson
      - yaml
      - unliftio-core
      - monad-logger
      - filepath
      - process
      - resourcet
      - conduit
      - conduit-extra
      - optparse-applicative
      - ansi-terminal
      - base16-bytestring
      - network-transport
      - distributed-process
      # TODO for debugging
      - pretty-simple
    ghc-options: *exe-ghc-options

tests:

  smtlib2-test:
    source-dirs: components/tests/smtlib2-test
    main: Main
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:smtlib2-process
      - sel4-bv:target-dir
      - sel4-bv:test-utils
      # external
      - attoparsec
      - megaparsec
      - filepath
      - process
      - Glob
      - tasty
      - tasty-hunit
    ghc-options: *test-ghc-options

  logging-test:
    source-dirs: components/tests/logging-test
    main: Main
    dependencies:
      - sel4-bv:logging
      - sel4-bv:test-utils
      # external
      - attoparsec
      - attoparsec-aeson
      - aeson
      - monad-logger
      - tasty
      - tasty-hunit
    ghc-options: *test-ghc-options

  core-test:
    source-dirs: components/tests/core-test
    main: Main
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      - sel4-bv:system
      - sel4-bv:system-core
      - sel4-bv:test-utils
      # external
      - monad-logger
      - filepath
      - tasty
      - tasty-hunit
    ghc-options: *test-ghc-options

  concrete-syntax-test:
    source-dirs: components/tests/concrete-syntax-test
    main: Main
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      - sel4-bv:test-utils
      # external
      - attoparsec
      - megaparsec
      - aeson
      - filepath
      - process
      - Glob
      - tasty
      - tasty-hunit
    ghc-options: *test-ghc-options

  system-test:
    source-dirs: components/tests/system-test
    main: Main
    dependencies:
      - sel4-bv:system
      - sel4-bv:system-core
      - sel4-bv:test-utils
    ghc-options: *test-ghc-options

  search-test:
    source-dirs: components/tests/search-test
    main: Main
    dependencies:
      - sel4-bv:core
      - sel4-bv:search-core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      - sel4-bv:system
      - sel4-bv:system-core
      - sel4-bv:search-system-core
      - sel4-bv:system-utils
      - sel4-bv:smtlib2
      - sel4-bv:smtlib2-process
      - sel4-bv:test-utils
      - sel4-bv:logging
      # external
      - unliftio-core
      - monad-logger
      - resourcet
      - filepath
      - process
      - tasty
      - tasty-hunit
    ghc-options: *test-ghc-options

# NOTES

# - pretty-show
# - pretty-simple
