spec-version: 0.36.0
name: sel4-bv
version: 0.1.0.0
synopsis: TODO
description: TODO
license: BSD-2-Clause
author: Nick Spinale (Colias Group, LLC)
maintainer: Nick Spinale <nick@nickspinale.com>
copyright: Copyright (c) 2025 Colias Group, LLC

language: GHC2021

default-extensions:
  - FunctionalDependencies
  # records
  - DuplicateRecordFields
  - NoFieldSelectors
  - OverloadedLabels
  - OverloadedRecordDot
  # GHC2024
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - LambdaCase

ghc-options:
  - -Wall
  - -Wno-unused-do-bind

dependencies:
  - base
  - deepseq
  - parallel
  - transformers
  - mtl
  - exceptions
  - containers
  - bytestring
  - text
  - stm
  - async
  - optics

internal-libraries:

  smtlib2:
    visibility: public
    source-dirs: components/smtlib2
    exposed-modules:
      - BV.SMTLIB2
      - BV.SMTLIB2.Command
      - BV.SMTLIB2.Monad
      - BV.SMTLIB2.SExpr
      - BV.SMTLIB2.SExpr.Show
      - BV.SMTLIB2.SExpr.Read
      - BV.SMTLIB2.SExpr.Build
      - BV.SMTLIB2.SExpr.Parse.Attoparsec
      - BV.SMTLIB2.SExpr.Parse.Megaparsec
    dependencies:
      - attoparsec
      - megaparsec

  smtlib2-process:
    visibility: public
    source-dirs: components/smtlib2-process
    exposed-modules:
      - BV.SMTLIB2.Process
    dependencies:
      - sel4-bv:smtlib2
      # external
      - process
      - unliftio-core
      - conduit
      - conduit-extra
  
  core:
    visibility: public
    source-dirs: components/core
    exposed-modules:
      - BV.Core.Types
      - BV.Core.Types.Extras
      - BV.Core.Stages
      - BV.Core.AdornProofScript
      - BV.Core.ExecuteSMTProofChecks
    dependencies:
      - sel4-bv:smtlib2
      # external
      - file-embed
      # TODO for debugging
      - filepath
      - pretty-show
      # - pretty-simple

  concrete-syntax:
    visibility: public
    source-dirs: components/concrete-syntax
    exposed-modules:
      - BV.ConcreteSyntax
    dependencies:
      - sel4-bv:core
      - sel4-bv:smtlib2
      # external
      - dlist
      - megaparsec
      - attoparsec
      - aeson
      - aeson-pretty

  target-dir:
    visibility: public
    source-dirs: components/target-dir
    exposed-modules:
      - BV.TargetDir
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      # external
      - aeson
      - filepath

  system:
    visibility: public
    source-dirs: components/system
    # exposed-modules: # TODO
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:smtlib2-process
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      # external
      - base16-bytestring
      - cryptohash-sha256
      - attoparsec
      - megaparsec
      - process
      - filepath
      - directory
      - monad-logger
      - unliftio-core
      # TODO prune
      - pretty-show
      # - pretty-simple
      # TODO hack
      - tasty
      - tasty-hunit

  test-utils:
    source-dirs: components/tests/test-utils
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      # external
      - filepath
      # TODO prune
      - pretty-show
      # - pretty-simple

executables:

  cli:
    source-dirs: components/cli
    main: Main.hs
    dependencies:
      - sel4-bv:system
    ghc-options:
      # TODO probably unnecessary here
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  normalize-smtlib2:
    source-dirs: components/utils/normalize-smtlib2
    main: Main.hs
    dependencies:
      - sel4-bv:smtlib2

  profiling-scratch:
    source-dirs: components/scratch/profiling-scratch
    main: Main.hs
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:system
      - sel4-bv:test-utils
    ghc-options:
      # TODO probably unnecessary here
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  check-scratch:
    source-dirs: components/scratch/check-scratch
    main: Main.hs
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:core
      - sel4-bv:system
      - sel4-bv:test-utils
      # external
      - filepath
    ghc-options:
      # TODO probably unnecessary here
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:

  core-test:
    source-dirs: components/tests/core-test
    main: Main.hs
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      - sel4-bv:system
      - sel4-bv:test-utils
      # external
      - monad-logger
      - filepath
      - tasty
      - tasty-hunit
    ghc-options:
      # TODO
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  smtlib2-test:
    source-dirs: components/tests/smtlib2-test
    main: Main.hs
    dependencies:
      - sel4-bv:smtlib2
      - sel4-bv:smtlib2-process
      - sel4-bv:target-dir
      # external
      - attoparsec
      - megaparsec
      - filepath
      - process
      - Glob
      - tasty
      - tasty-hunit
    ghc-options:
      # TODO
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  concrete-syntax-test:
    source-dirs: components/tests/concrete-syntax-test
    main: Main.hs
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:target-dir
      - sel4-bv:test-utils
      # external
      - attoparsec
      - megaparsec
      - aeson
      - filepath
      - process
      - Glob
      - tasty
      - tasty-hunit
    ghc-options:
      # TODO
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  system-test:
    source-dirs: components/tests/system-test
    main: Main.hs
    dependencies:
      - sel4-bv:system
    ghc-options:
      # TODO
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
