steps:
  - module_header: {}
  - records:
      equals: "indent 2"
      first_field: "indent 2"
      field_comment: 2
      deriving: 2
      via: "indent 2"
      break_enums: true
  # - simple_align: {}
  - imports:
      # align: global
      align: none
      pad_module_names: false
  - language_pragmas:
      align: false
  - tabs:
      spaces: 4
  - trailing_whitespace: {}
  - squash: {}
