spec-version: 0.36.0
name: sel4-bv
version: 0.1.0.0
synopsis: TODO
description: TODO
license: BSD-2-Clause
author: Nick Spinale (Colias Group, LLC)
maintainer: Nick Spinale <nick@nickspinale.com>
copyright: Copyright (c) 2025 Colias Group, LLC

language: GHC2021

default-extensions:
  - FunctionalDependencies
  # records
  - DuplicateRecordFields
  - NoFieldSelectors
  - OverloadedLabels
  - OverloadedRecordDot
  # GHC2024
  - DerivingStrategies
  - LambdaCase

ghc-options:
  - -Wall
  - -Wno-unused-do-bind

dependencies:
  - base

internal-libraries:

  smtlib2-types:
    visibility: public
    source-dirs: components/smtlib2-types
    # exposed-modules: # TODO
    dependencies:
      - deepseq

  smtlib2:
    visibility: public
    source-dirs: components/smtlib2
    # exposed-modules: # TODO
    dependencies:
      - sel4-bv:smtlib2-types
      # external
      - text
      - attoparsec
      - megaparsec
      - conduit
      - conduit-extra
  
  core:
    visibility: public
    source-dirs: components/core
    # exposed-modules: # TODO
    dependencies:
      - sel4-bv:smtlib2-types
      # external
      - deepseq
      - containers
      - monad-logger
      - mtl
      - optics-core
      # - pretty-show
      # - pretty-simple

  concrete-syntax:
    visibility: public
    source-dirs: components/concrete-syntax
    exposed-modules:
      - BV.ConcreteSyntax
    dependencies:
      - sel4-bv:core
      - sel4-bv:smtlib2-types
      # external
      - containers
      - dlist
      - optics-core
      - text
      - attoparsec
      - megaparsec
      # TODO remove
      - bytestring
      - aeson
      - attoparsec-aeson

  system:
    visibility: public
    source-dirs: components/system
    # exposed-modules: # TODO
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:smtlib2
      - sel4-bv:abstract-simple-smt
      # external
      - deepseq
      - containers
      - mtl
      - transformers
      - optics-core
      - async
      - stm
      - bytestring
      - text
      - attoparsec
      - megaparsec
      - filepath
      - monad-logger
      - simple-smt
      # TODO assess
      - free
      - extensible-effects
      - kan-extensions
      # TODO prune
      - pretty-show
      - pretty-simple
      # TODO hack
      - tasty
      - tasty-hunit
      # TODO temporary
      - ghc-datasize

  abstract-simple-smt:
    visibility: public
    source-dirs: components/abstract-simple-smt
    dependencies:
      - transformers
      - mtl
      - simple-smt

executables:

  cli:
    source-dirs: components/cli
    main: Main.hs
    dependencies:
      - sel4-bv:system
    ghc-options:
      # TODO probably unnecessary here
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  profiling-scratch:
    source-dirs: components/profiling-scratch
    main: Main.hs
    dependencies:
      - sel4-bv:core
      - sel4-bv:concrete-syntax
      - sel4-bv:system
      #
      - text
    ghc-options:
      # TODO probably unnecessary here
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:

  smtlib2-test:
    source-dirs: components/smtlib2-test
    main: Main.hs
    dependencies:
      - sel4-bv:smtlib2
      # external
      - text
      - attoparsec
      - megaparsec
      - conduit
      - conduit-extra
      # external
      - tasty
      - tasty-hunit

  test:
    source-dirs: components/test
    main: Main.hs
    dependencies:
      - sel4-bv:system
      # external
      - tasty
      - tasty-hunit
