spec-version: 0.36.0
name: bv
version: 0.1.0.0
synopsis: TODO
description: TODO
license: BSD-2-Clause
author: Nick Spinale (Colias Group, LLC)
maintainer: Nick Spinale <nick@nickspinale.com>
copyright: Copyright (c) 2025 Colias Group, LLC

language: GHC2021

default-extensions:
  - DuplicateRecordFields
  - FunctionalDependencies
  - LambdaCase
  - NoFieldSelectors
  - OverloadedLabels
  - OverloadedRecordDot

ghc-options:
  - -Wall
  - -Wno-unused-do-bind

dependencies:
  - base

library:
  source-dirs: components/dummy
  dependencies:
    - bv-core
    - bv-concrete-syntax
    - bv-system
    - abstract-simple-smt

internal-libraries:
  bv-core:
    visibility: public
    source-dirs: components/core
    # exposed-modules: # TODO
    dependencies:
      - abstract-simple-smt
      #
      - containers
      - monad-logger
      - mtl
      - optics-core
      # TODO prune
      - pretty-show
      - pretty-simple
  bv-concrete-syntax:
    visibility: public
    source-dirs: components/concrete-syntax
    exposed-modules:
      - BV.ConcreteSyntax
    dependencies:
      - bv-core
      #
      - aeson
      - attoparsec
      - attoparsec-aeson
      - containers
      - dlist
      - megaparsec
      - optics-core
      - text
  bv-system:
    visibility: public
    source-dirs: components/system
    # exposed-modules: # TODO
    dependencies:
      - bv-core
      - bv-concrete-syntax
      - abstract-simple-smt
      #
      - aeson
      - async
      - attoparsec-aeson
      - attoparsec
      - containers
      - dlist
      - filepath
      - megaparsec
      - monad-logger
      - mtl
      - optics-core
      - simple-smt
      - stm
      - text
      # TODO assess
      - extensible-effects
      - free
      - kan-extensions
      # TODO prune
      - pretty-show
      - pretty-simple
      # TODO hack
      - tasty
      - tasty-hunit
      # TODO temporary
      - ghc-datasize
  abstract-simple-smt:
    visibility: public
    source-dirs: components/abstract-simple-smt
    dependencies:
      - mtl
      - simple-smt
      - transformers

# TODO
# executable:
#   source-dirs: components/dummy
#   dependencies:
#     - bv-system
#     - abstract-simple-smt

executables:
  bv-cli:
    source-dirs: components/cli
    main: Main.hs
    dependencies:
      - bv-system
    ghc-options:
      # TODO probably unnecessary here
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  test:
    source-dirs: components/test
    main: Main.hs
    dependencies:
      - bv-system
